name: "CI Builds"
on:
  push:
    tags-ignore:
      - "v*.*.*"
    branches:
      - '**'

jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - debian.11
          - fedora.42
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp
