name: "Build and release binaries"
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - debian.11
          - debian.12
          - debian.13
          - fedora.41
          - fedora.42
          - opensuse.15.6
          - opensuse.tumbleweed
          - rhel.8
          - rhel.9
          - rhel.10
          - ubuntu.22.04
          - ubuntu.24.04
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp
      - uses: softprops/action-gh-release@v2
        with:
          files: veyon*
